# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/lukechampine/uint128
%global goipath         go4.org/netipx
URL:                    https://github.com/go4org/netipx
Version:                0

%gometa -f

%global common_description %{expand:
Uint128 for Go.}

%global golicenses      LICENSE
%global godocs          README.md
%global tag             main
%global archivename     netipx-%{tag}

Name:           %{goname}
Release:        %autorelease
Summary:        extra stuff from inet.af/netaddr that didn't make it into Go's net/netip

License:        MIT
Source:         https://github.com/go4org/netipx/archive/refs/heads/main.tar.gz#/netipx-main.tar.gz

%description %{common_description}

%gopkg

%prep
%goprep
mv %{archivename}/* ./
rm -rfv %{archivename}
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
